# Generated by Django 4.1.6 on 2023-02-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='pais',
            field=models.CharField(default='', max_length=35),
        ),
    ]
